// AUTO-GENERATED by demo/demo.js from packages/core/src/events.json — DO NOT EDIT (chay: npm run demo)
import { Component, AfterViewInit, ViewChild, ElementRef, HostListener } from '@angular/core';
import {
  MiniApp,
  getSharedMiniApp,
  appOpenWebview,
  appOpenStore,
  exit,
  openExternalLink,
  openMiniApp,
  requestMultipleUserDataPermission,
  checkMultipleUserDataPermission,
  getMultipleUserData,
  clearPermissionCache,
  requestCameraPermission,
  requestLocationPermission,
  requestPhotosPermission,
  requestVideosPermission,
  requestAudioPermission,
  requestRecordAudioPermission,
  requestContactsPermission,
  requestDocumentPermission,
  requestPaymentPermission,
  requestLoginPermission,
  requestLocalAuthenticationPermission,
  checkCameraPermission,
  checkLocationPermission,
  checkPhotosPermission,
  checkVideosPermission,
  checkAudioPermission,
  checkRecordAudioPermission,
  checkContactsPermission,
  checkDocumentPermission,
  checkPaymentPermission,
  checkLoginPermission,
  checkLocalAuthenticationPermission,
  executeLocalAuthentication,
  getLocalAuthenticationStatus,
  getContacts,
  saveStringValue,
  saveBooleanValue,
  saveIntegerValue,
  saveLongValue,
  saveFloatValue,
  getStringValue,
  getBooleanValue,
  getIntegerValue,
  getLongValue,
  getFloatValue,
  clearStorage,
  getLocation,
  shareTextContent,
  miniAppToken,
  updateMiniAppTheme,
  expiredSession,
  saveImageToGallery,
  saveFile,
  openInAppDeeplink,
  initRequest,
  setScreenBrightness,
  restoreScreenBrightness,
  openSmsComposer,
  setCurrentPage,
} from 'vdf-webview-miniapp-sdk';

interface EventInfo {
  name: string;
  event: string;
  desc: string;
  hasParams: boolean;
  defaultData: string | null;
  responseSample: string | null;
}


function selectBetweenChar(el: HTMLTextAreaElement, char: string): void {
  const pos = el.selectionStart ?? 0;
  const text = el.value;
  const start = text.lastIndexOf(char, pos - 1);
  const end = text.indexOf(char, pos);
  if (start === -1 || end === -1) return;
  el.focus();
  el.setSelectionRange(start + 1, end);
}
function setupSmartTap(el: HTMLTextAreaElement): void {
  let tapCount = 0;
  let tapTimer: ReturnType<typeof setTimeout> | null = null;
  el.addEventListener('touchend', () => {
    tapCount++;
    if (tapTimer) clearTimeout(tapTimer);
    tapTimer = setTimeout(() => {
      if (tapCount >= 3) selectBetweenChar(el, '"');
      tapCount = 0;
    }, 300);
  });
}
function setupLongPress(el: HTMLElement, onLongPress: () => void, duration = 600): void {
  let timer: ReturnType<typeof setTimeout> | null = null;
  const start = () => {
    el.classList.add('long-pressing');
    timer = setTimeout(() => { timer = null; onLongPress(); el.classList.remove('long-pressing'); }, duration);
  };
  const cancel = () => { if (timer) { clearTimeout(timer); timer = null; } el.classList.remove('long-pressing'); };
  el.addEventListener('touchstart', start, { passive: true });
  el.addEventListener('touchend', cancel);
  el.addEventListener('touchmove', cancel);
}


function genRequestId(): string {
  return 'req_' + Date.now() + '_' + Math.random().toString(36).slice(8);
}
function buildRawSnippet(eventName: string, payload: any, responseSample: string | null): string {
  const requestId = genRequestId();
  const request: Record<string, any> = { event: eventName, sender: '', request_id: '' };
  if (payload && typeof payload === 'object') {
    Object.keys(payload).forEach(k => { request[k] = payload[k]; });
  }
  request['sender'] = 'MINIAPP_WEBVIEW';
  request['request_id'] = requestId;
  request['requestId'] = requestId;
  request['timestamp'] = Date.now();

  const response: Record<string, any> = {
    event: request['event'],
    sender: 'MINIAPP_SDK',
    response_id: 'res_...',
    request_id: requestId,
  };
  if (responseSample) {
    const data = JSON.parse(responseSample);
    Object.keys(data).forEach(k => { response[k] = data[k]; });
  }
  response['eventStatus'] = { errorCode: 'SDK000', errorMessageVN: 'Thanh cong', errorMessageEN: 'Success', realMsg: '' };
  const resLines = JSON.stringify(response, null, 2).split('\n').map(l => '  // ' + l).join('\n');
  return [
    '// ---- ' + request['event'] + ' — goi truc tiep, KHONG dung web SDK ----',
    '// request_id va timestamp do phia mini app tu sinh moi lan goi.',
    '// Host co cap token thi them truong "token" cung cap voi "event".',
    '',
    '// 1) JSON gui xuong native',
    'var json = JSON.stringify(' + JSON.stringify(request, null, 2) + ');',
    '',
    '// 2) Gui di — chon theo nen tang dang chay',
    'if (window.AndroidWebview) {',
    '  window.AndroidWebview.miniappWebviewToSdk(json);',
    '} else if (window.webkit && window.webkit.messageHandlers.miniappWebviewToSdk) {',
    '  window.webkit.messageHandlers.miniappWebviewToSdk.postMessage(json);',
    '} else if (window.miniappSdkToWebview) {',
    '  window.miniappSdkToWebview(json); // web: loopback de tu test',
    '}',
    '',
    '// 3) Nhan ve — native goi ham nay, tu khop theo request_id',
    'window.miniappSdkToWebview = function (raw) {',
    '  var res = typeof raw === "string" ? JSON.parse(raw) : raw;',
    '  // res =',
    resLines,
    '};'
  ].join('\n');
}
function copyText(text: string): void {
  if (navigator.clipboard && navigator.clipboard.writeText) { navigator.clipboard.writeText(text); return; }
  const ta = document.createElement('textarea');
  ta.value = text;
  ta.style.position = 'fixed';
  ta.style.opacity = '0';
  document.body.appendChild(ta);
  ta.select();
  try { document.execCommand('copy'); } catch (e) { /* webview cu khong ho tro */ }
  document.body.removeChild(ta);
}

@Component({
  selector: 'app-root',
  templateUrl: 'app.component.html',
  styleUrls: ['app.component.scss'],
})
export class AppComponent implements AfterViewInit {

  inputs: Record<string, string> = {};
  eventLogs: Record<string, string[]> = {};
  popup: EventInfo | null = null;
  rawText: string | null = null;
  private app: MiniApp;
  private smartTapReady = new WeakSet<HTMLTextAreaElement>();

  // Event registry
  private fns: Record<string, () => Promise<any>> = {};

  constructor() {
    this.app = getSharedMiniApp({ debug: true });
    this.app.ready();
    this.registerFns();
  }

  ngAfterViewInit(): void {
    document.querySelectorAll<HTMLElement>('.btn[data-evt]').forEach(btn => {
      const evtName = btn.dataset['evt']!;
      const evt = this.groups.flatMap(g => g.events).find(e => e.name === evtName);
      if (evt) setupLongPress(btn, () => this.quickRun(evt));
    });
  }

  onInputFocus(e: FocusEvent): void {
    const el = e.target as HTMLTextAreaElement;
    if (!this.smartTapReady.has(el)) { this.smartTapReady.add(el); setupSmartTap(el); }
  }

  getInputStr(name: string): string { return this.inputs[name] || ''; }
  setInputStr(name: string, val: string): void { this.inputs[name] = val; }
  getLogsStr(name: string): string {
    const l = this.eventLogs[name] || [];
    return l.length ? l.join('\n') : 'No logs yet.';
  }

  private getInputFor_(name: string): any {
    const v = (this.inputs[name] || '').trim();
    if (!v) return null;
    try { return JSON.parse(v); } catch { return null; }
  }

  quickRun(evt: EventInfo): void {
    const saved = localStorage.getItem(this.lsKey(evt.name));
    if (saved) { try { this.inputs[evt.name] = JSON.stringify(JSON.parse(saved), null, 2); } catch { this.inputs[evt.name] = saved; } }
    else if (evt.defaultData) this.inputs[evt.name] = JSON.stringify(JSON.parse(evt.defaultData), null, 2);
    this.runEvent(evt);
  }

  private registerFns(): void {
    this.fns['appOpenWebview'] = () => appOpenWebview(this.getInputFor_('appOpenWebview') || {"data":{"url":"https://example.com","serviceName":"Tên dịch vụ","isPaymentConfirm":false,"resourceType":"HTML","returnUrl":"https://example.com/return","cancelUrl":"https://example.com/cancel"}});
    this.fns['appOpenStore'] = () => appOpenStore(this.getInputFor_('appOpenStore') || {"data":{"fallbackUrlAndroid":"viettelpay://action/c=FECRDT&t=FINANCE4","fallbackUrlIos":"viettelpay://action/c=FECRDT&t=FINANCE4","needToExitMiniApp":true,"package":"null","appId":"null"}});
    this.fns['exit'] = () => exit(this.getInputFor_('exit') || {"data":{"navigationAction":"..."}});
    this.fns['openExternalLink'] = () => openExternalLink(this.getInputFor_('openExternalLink') || {"data":{"uri":"https://google.com"}});
    this.fns['openMiniApp'] = () => openMiniApp(this.getInputFor_('openMiniApp') || {"data":{"route":{"screenName":"home"},"miniAppKey":"01K5FY191HP42SMMJXHWG545ZZ","additional":{"param1":"value1","param2":"value2"},"launchConfig":{"mode":"present"},"themeConfig":{"title":"My App","headerColor":"#EE0033","headerTitle":"Videos","textColor":"white","leftButton":"back","actionButtonThemeType":"normal","hideAndroidBottomNavigationBar":true,"hideIOSSafeAreaBottom":true},"tracking":{"campaign":"promotion","utmSource":"miniapp"}}});
    this.fns['requestMultipleUserDataPermission'] = () => requestMultipleUserDataPermission(this.getInputFor_('requestMultipleUserDataPermission') || {"data":{"permissionCodes":["USER_AGE_PERMISSION","USER_NAME_PERMISSION","USER_FULL_NAME_PERMISSION","USER_PHONE_NUMBER_PERMISSION","USER_AVATAR_PERMISSION","USER_BIRTH_DATE_PERMISSION","USER_GENDER_PERMISSION","USER_NATIONAL_ID_PERMISSION"],"useSameReason":true}});
    this.fns['checkMultipleUserDataPermission'] = () => checkMultipleUserDataPermission(this.getInputFor_('checkMultipleUserDataPermission') || {"data":{"permissionCodes":["USER_AGE_PERMISSION","USER_NAME_PERMISSION","USER_FULL_NAME_PERMISSION","USER_PHONE_NUMBER_PERMISSION","USER_AVATAR_PERMISSION","USER_BIRTH_DATE_PERMISSION","USER_GENDER_PERMISSION","USER_NATIONAL_ID_PERMISSION"]}});
    this.fns['getMultipleUserData'] = () => getMultipleUserData(this.getInputFor_('getMultipleUserData') || {"data":{"dataNames":["age","userName","fullName","phoneNumber","avatar","gender","birthday","idNo"]}});
    this.fns['clearPermissionCache'] = () => clearPermissionCache(this.getInputFor_('clearPermissionCache') || {"data":{}});
    this.fns['requestCameraPermission'] = () => requestCameraPermission();
    this.fns['requestLocationPermission'] = () => requestLocationPermission();
    this.fns['requestPhotosPermission'] = () => requestPhotosPermission();
    this.fns['requestVideosPermission'] = () => requestVideosPermission();
    this.fns['requestAudioPermission'] = () => requestAudioPermission();
    this.fns['requestRecordAudioPermission'] = () => requestRecordAudioPermission();
    this.fns['requestContactsPermission'] = () => requestContactsPermission();
    this.fns['requestDocumentPermission'] = () => requestDocumentPermission();
    this.fns['requestPaymentPermission'] = () => requestPaymentPermission();
    this.fns['requestLoginPermission'] = () => requestLoginPermission();
    this.fns['requestLocalAuthenticationPermission'] = () => requestLocalAuthenticationPermission();
    this.fns['checkCameraPermission'] = () => checkCameraPermission();
    this.fns['checkLocationPermission'] = () => checkLocationPermission();
    this.fns['checkPhotosPermission'] = () => checkPhotosPermission();
    this.fns['checkVideosPermission'] = () => checkVideosPermission();
    this.fns['checkAudioPermission'] = () => checkAudioPermission();
    this.fns['checkRecordAudioPermission'] = () => checkRecordAudioPermission();
    this.fns['checkContactsPermission'] = () => checkContactsPermission();
    this.fns['checkDocumentPermission'] = () => checkDocumentPermission();
    this.fns['checkPaymentPermission'] = () => checkPaymentPermission();
    this.fns['checkLoginPermission'] = () => checkLoginPermission();
    this.fns['checkLocalAuthenticationPermission'] = () => checkLocalAuthenticationPermission();
    this.fns['executeLocalAuthentication'] = () => executeLocalAuthentication(this.getInputFor_('executeLocalAuthentication') || {"data":{"authOptionsParam":{"sensitiveTransaction":true,"authClassification":["WEAK","STRONG","DEVICE"],"sticky":false,"isShowErrorDialog":true}}});
    this.fns['getLocalAuthenticationStatus'] = () => getLocalAuthenticationStatus();
    this.fns['getContacts'] = () => getContacts(this.getInputFor_('getContacts') || {"data":{"filter":{"contactName":"John"},"pager":{"pageNumber":1,"limitRow":100}}});
    this.fns['saveStringValue'] = () => saveStringValue(this.getInputFor_('saveStringValue') || {"data":{"key":"user_preference","value":"dark_mode"}});
    this.fns['saveBooleanValue'] = () => saveBooleanValue(this.getInputFor_('saveBooleanValue') || {"data":{"key":"notifications_enabled","value":true}});
    this.fns['saveIntegerValue'] = () => saveIntegerValue(this.getInputFor_('saveIntegerValue') || {"data":{"key":"login_count","value":5}});
    this.fns['saveLongValue'] = () => saveLongValue(this.getInputFor_('saveLongValue') || {"data":{"key":"last_sync_timestamp","value":1234567890}});
    this.fns['saveFloatValue'] = () => saveFloatValue(this.getInputFor_('saveFloatValue') || {"data":{"key":"rating","value":4.5}});
    this.fns['getStringValue'] = () => getStringValue(this.getInputFor_('getStringValue') || {"data":{"key":"user_preference","defaultValue":"light_mode"}});
    this.fns['getBooleanValue'] = () => getBooleanValue(this.getInputFor_('getBooleanValue') || {"data":{"key":"notifications_enabled","defaultValue":false}});
    this.fns['getIntegerValue'] = () => getIntegerValue(this.getInputFor_('getIntegerValue') || {"data":{"key":"...","defaultValue":0}});
    this.fns['getLongValue'] = () => getLongValue(this.getInputFor_('getLongValue') || {"data":{"key":"...","defaultValue":0}});
    this.fns['getFloatValue'] = () => getFloatValue(this.getInputFor_('getFloatValue') || {"data":{"key":"...","defaultValue":"..."}});
    this.fns['clearStorage'] = () => clearStorage();
    this.fns['getLocation'] = () => getLocation();
    this.fns['shareTextContent'] = () => shareTextContent(this.getInputFor_('shareTextContent') || {"data":{"content":"Check out this amazing product!"}});
    this.fns['miniAppToken'] = () => miniAppToken();
    this.fns['updateMiniAppTheme'] = () => updateMiniAppTheme(this.getInputFor_('updateMiniAppTheme') || {"data":{"headerColor":"#FFFFFF","headerTitle":"Mini App","textColor":"#EE0033","leftButton":"back","actionButtonThemeType":"light","hideAndroidBottomNavigationBar":false,"hideIOSSafeAreaBottom":false,"toolbarMode":"normal"}});
    this.fns['expiredSession'] = () => expiredSession();
    this.fns['saveImageToGallery'] = () => saveImageToGallery(this.getInputFor_('saveImageToGallery') || {"data":{"type":"url","data":"https://media-cdn-v2.laodong.vn/storage/newsportal/2023/8/26/1233821/Giai-Nhat--Dem-Sai-G.jpg"}});
    this.fns['saveFile'] = () => saveFile(this.getInputFor_('saveFile') || {"data":{"url":"https://pdfobject.com/pdf/sample.pdf","fileName":"test_file"}});
    this.fns['openInAppDeeplink'] = () => openInAppDeeplink(this.getInputFor_('openInAppDeeplink') || {"data":{"url":"viettelpay://action/c=FECRDT&t=FINANCE4"}});
    this.fns['initRequest'] = () => initRequest();
    this.fns['setScreenBrightness'] = () => setScreenBrightness(this.getInputFor_('setScreenBrightness') || {"data":{"value":0.8}});
    this.fns['restoreScreenBrightness'] = () => restoreScreenBrightness(this.getInputFor_('restoreScreenBrightness') || {"data":{}});
    this.fns['openSmsComposer'] = () => openSmsComposer(this.getInputFor_('openSmsComposer') || {"data":{"recipient":"+84987654321","body":"Xin chao tu mini-app"}});
    this.fns['setCurrentPage'] = () => setCurrentPage(this.getInputFor_('setCurrentPage') || {"data":{"pageId":"home","pageName":"Trang chủ"}});
    this.fns['invoke'] = () => this.app.invoke(this.getInputFor_('invoke')?.event || 'GET_LOCATION', this.getInputFor_('invoke'));
  }

  // Event groups
  groups: { title: string; events: EventInfo[] }[] = [
    { title: 'Routing', events: [
      { name: 'appOpenWebview', event: 'APP_OPEN_WEBVIEW', desc: 'Mở một WebView mới với URL và cấu hình tùy chỉnh.', hasParams: true, defaultData: '{"data":{"url":"https://example.com","serviceName":"Tên dịch vụ","isPaymentConfirm":false,"resourceType":"HTML","returnUrl":"https://example.com/return","cancelUrl":"https://example.com/cancel"}}', responseSample: "{\"data\":{\"url\":\"https://example.com/return?status=success\",\"type\":\"RETURN\"}}" },
      { name: 'appOpenStore', event: 'APP_OPEN_STORE', desc: 'Mở ứng dụng từ App Store/Google Play hoặc launch app đã cài.', hasParams: true, defaultData: '{"data":{"fallbackUrlAndroid":"viettelpay://action/c=FECRDT&t=FINANCE4","fallbackUrlIos":"viettelpay://action/c=FECRDT&t=FINANCE4","needToExitMiniApp":true,"package":"null","appId":"null"}}', responseSample: null },
      { name: 'exit', event: 'EXIT', desc: 'Đóng Mini App và điều hướng về màn hình khác.', hasParams: true, defaultData: '{"data":{"navigationAction":"..."}}', responseSample: null },
      { name: 'openExternalLink', event: 'OPEN_EXTERNAL_LINK', desc: 'Mở URL bằng browser mặc định của hệ thống.', hasParams: true, defaultData: '{"data":{"uri":"https://google.com"}}', responseSample: null },
      { name: 'openMiniApp', event: 'OPEN_MINI_APP', desc: 'Mở một Mini App khác từ Mini App hiện tại.', hasParams: true, defaultData: '{"data":{"route":{"screenName":"home"},"miniAppKey":"01K5FY191HP42SMMJXHWG545ZZ","additional":{"param1":"value1","param2":"value2"},"launchConfig":{"mode":"present"},"themeConfig":{"title":"My App","headerColor":"#EE0033","headerTitle":"Videos","textColor":"white","leftButton":"back","actionButtonThemeType":"normal","hideAndroidBottomNavigationBar":true,"hideIOSSafeAreaBottom":true},"tracking":{"campaign":"promotion","utmSource":"miniapp"}}}', responseSample: null },
      { name: 'openInAppDeeplink', event: 'OPEN_IN_APP_DEEPLINK', desc: 'Mở deeplink nội bộ app', hasParams: true, defaultData: '{"data":{"url":"viettelpay://action/c=FECRDT&t=FINANCE4"}}', responseSample: "{\"data\":{\"success\":true}}" },
      { name: 'openSmsComposer', event: 'OPEN_SMS_COMPOSER', desc: 'Mở trình soạn tin nhắn của hệ điều hành với số nhận và nội dung điền sẵn. SDK KHÔNG gửi tin — người dùng tự bấm gửi trong trình soạn tin. ⚠️ Mở thành công trả về mã SDK852, KHÔNG phải SDK000, nên `isSuccess()` trả false và Promise bị REJECT dù mọi thứ đúng: hãy đọc kết quả trong nhánh `catch`, giá trị nhận được là nguyên response (đọc `data.terminal_state`). Đây là hành vi đã biết và được chấp nhận, không phải lỗi. Trên iOS còn một nhịp thứ hai mang kết cục thật, và nhịp đó KHÔNG đến qua Promise — phải nghe bằng `app.on(\'OPEN_SMS_COMPOSER\', cb)`.', hasParams: true, defaultData: '{"data":{"recipient":"+84987654321","body":"Xin chao tu mini-app"}}', responseSample: "{\"data\":{\"terminal_state\":\"HANDED_OFF\"}}" }
    ] },
    { title: 'UserData Permission', events: [
      { name: 'requestMultipleUserDataPermission', event: 'REQUEST_MULTIPLE_USER_DATA_PERMISSION', desc: 'Yêu cầu nhiều quyền user data cùng một lúc.', hasParams: true, defaultData: '{"data":{"permissionCodes":["USER_AGE_PERMISSION","USER_NAME_PERMISSION","USER_FULL_NAME_PERMISSION","USER_PHONE_NUMBER_PERMISSION","USER_AVATAR_PERMISSION","USER_BIRTH_DATE_PERMISSION","USER_GENDER_PERMISSION","USER_NATIONAL_ID_PERMISSION"],"useSameReason":true}}', responseSample: "{\"data\":[]}" },
      { name: 'checkMultipleUserDataPermission', event: 'CHECK_MULTIPLE_USER_DATA_PERMISSION', desc: 'Kiểm tra trạng thái nhiều quyền user data cùng lúc.', hasParams: true, defaultData: '{"data":{"permissionCodes":["USER_AGE_PERMISSION","USER_NAME_PERMISSION","USER_FULL_NAME_PERMISSION","USER_PHONE_NUMBER_PERMISSION","USER_AVATAR_PERMISSION","USER_BIRTH_DATE_PERMISSION","USER_GENDER_PERMISSION","USER_NATIONAL_ID_PERMISSION"]}}', responseSample: "{\"data\":[]}" }
    ] },
    { title: 'Get data event', events: [
      { name: 'getMultipleUserData', event: 'GET_MULTIPLE_USER_DATA', desc: 'Lấy nhiều trường dữ liệu người dùng từ host app.', hasParams: true, defaultData: '{"data":{"dataNames":["age","userName","fullName","phoneNumber","avatar","gender","birthday","idNo"]}}', responseSample: "{\"age\":\"...\",\"userName\":\"...\",\"fullName\":\"...\",\"phoneNumber\":\"...\",\"avatar\":\"...\",\"gender\":\"...\",\"birthday\":\"...\",\"idNo\":\"...\"}" },
      { name: 'getLocalAuthenticationStatus', event: 'GET_LOCAL_AUTHENTICATION_STATUS', desc: ' lấy trạng thái xác thực sinh trắc học (vân tay, Face ID).', hasParams: false, defaultData: null, responseSample: "{\"isHardwareSupportStrongBiometric\":true,\"isHardwareSupportBiometric\":true,\"isDeviceSecure\":true,\"canAuthenticateWithDeviceCredential\":true,\"canAuthenticateWithBiometrics\":true,\"canAuthenticateWithStrongBiometrics\":true}" },
      { name: 'getContacts', event: 'GET_CONTACTS', desc: 'Lấy danh sách contacts từ danh bạ hệ thống. ', hasParams: true, defaultData: '{"data":{"filter":{"contactName":"John"},"pager":{"pageNumber":1,"limitRow":100}}}', responseSample: "{\"data\":{\"contactList\":[{\"contactName\":\"John Doe\",\"contactNumber\":\"0901234567\",\"contactAvt\":\"base64_image_string\"}],\"countContacts\":1}}" },
      { name: 'getLocation', event: 'GET_LOCATION', desc: 'Lấy vị trí GPS hiện tại của thiết bị. Phải có quyền LOCATION_PERMISSION trước khi sử dụng API này.', hasParams: false, defaultData: null, responseSample: "{\"latitude\":\"21.0285\",\"longgitude\":\"105.8542\"}" }
    ] },
    { title: 'Other', events: [
      { name: 'clearPermissionCache', event: 'CLEAR_PERMISSION_CACHE', desc: 'Xóa tất cả quyền đã cache ở local.', hasParams: true, defaultData: '{"data":{}}', responseSample: "{\"eventStatus\":{\"errorCode\":\"SDK000\"}}" },
      { name: 'shareTextContent', event: 'SHARE_TEXT_CONTENT', desc: 'Mở dialog chia sẻ nội dung text.', hasParams: true, defaultData: '{"data":{"content":"Check out this amazing product!"}}', responseSample: null },
      { name: 'miniAppToken', event: 'MINI_APP_TOKEN', desc: 'Get mini app token', hasParams: false, defaultData: null, responseSample: "{\"data\":{\"miniAppToken\":\"...\"}}" },
      { name: 'expiredSession', event: 'EXPIRED_SESSION', desc: 'Session expiration event, Delegate cho host app xử lý', hasParams: false, defaultData: null, responseSample: null },
      { name: 'saveImageToGallery', event: 'SAVE_IMAGE_TO_GALLERY', desc: 'Lưu ảnh vào bộ sưu tập', hasParams: true, defaultData: '{"data":{"type":"url","data":"https://media-cdn-v2.laodong.vn/storage/newsportal/2023/8/26/1233821/Giai-Nhat--Dem-Sai-G.jpg"}}', responseSample: "{\"data\":{\"success\":true}}" },
      { name: 'saveFile', event: 'SAVE_FILE', desc: 'Lưu file vào thư mục', hasParams: true, defaultData: '{"data":{"url":"https://pdfobject.com/pdf/sample.pdf","fileName":"test_file"}}', responseSample: "{\"data\":{\"success\":true}}" },
      { name: 'initRequest', event: 'INIT_REQUEST', desc: 'Get init event', hasParams: false, defaultData: null, responseSample: null },
      { name: 'setCurrentPage', event: 'SET_CURRENT_PAGE', desc: 'Báo cho app chủ biết trang mini-app vừa chuyển sang page nào. ⚠️ MỘT CHIỀU: entry này KHÔNG khai `response`, nên native không trả lời gì và hàm sinh ra trả về `void` — không có gì để `await`. SDK không đọc, không biến đổi, không gác quyền và không ghi bản ghi nào: event đi thẳng lên app chủ qua điểm mở rộng `intercept`, nên app chủ PHẢI `return true` ở đó. App chủ không nhận thì trang ăn một SDK100 mỗi lần chuyển trang.', hasParams: true, defaultData: '{"data":{"pageId":"home","pageName":"Trang chủ"}}', responseSample: null }
    ] },
    { title: 'Device Request Permission', events: [
      { name: 'requestCameraPermission', event: 'REQUEST_CAMERA_PERMISSION', desc: 'Yêu cầu mở camera', hasParams: false, defaultData: null, responseSample: "{\"permissionCode\":\"...\",\"result\":\"...\",\"message\":\"...\"}" },
      { name: 'requestLocationPermission', event: 'REQUEST_LOCATION_PERMISSION', desc: 'Yêu cầu vị trí', hasParams: false, defaultData: null, responseSample: "{\"permissionCode\":\"...\",\"result\":\"...\",\"message\":\"...\"}" },
      { name: 'requestPhotosPermission', event: 'REQUEST_PHOTOS_PERMISSION', desc: 'Yêu cầu truy cập ảnh trên thiết bị', hasParams: false, defaultData: null, responseSample: "{\"permissionCode\":\"...\",\"result\":\"...\",\"message\":\"...\"}" },
      { name: 'requestVideosPermission', event: 'REQUEST_VIDEOS_PERMISSION', desc: 'Yêu cầu truy cập video trên thiết bị', hasParams: false, defaultData: null, responseSample: "{\"permissionCode\":\"...\",\"result\":\"...\",\"message\":\"...\"}" },
      { name: 'requestAudioPermission', event: 'REQUEST_AUDIO_PERMISSION', desc: 'Yêu cầu truy cập audio trên thiết bị', hasParams: false, defaultData: null, responseSample: "{\"permissionCode\":\"...\",\"result\":\"...\",\"message\":\"...\"}" },
      { name: 'requestRecordAudioPermission', event: 'REQUEST_RECORD_AUDIO_PERMISSION', desc: 'Yêu cầu ghi âm trên thiết bị', hasParams: false, defaultData: null, responseSample: "{\"permissionCode\":\"...\",\"result\":\"...\",\"message\":\"...\"}" },
      { name: 'requestContactsPermission', event: 'REQUEST_CONTACTS_PERMISSION', desc: 'Yêu cầu truy cập danh bạ trên thiết bị', hasParams: false, defaultData: null, responseSample: "{\"permissionCode\":\"...\",\"result\":\"...\",\"message\":\"...\"}" },
      { name: 'requestDocumentPermission', event: 'REQUEST_DOCUMENT_PERMISSION', desc: 'Yêu cầu truy cập tài liệu trên thiết bị', hasParams: false, defaultData: null, responseSample: "{\"permissionCode\":\"...\",\"result\":\"...\",\"message\":\"...\"}" },
      { name: 'requestPaymentPermission', event: 'REQUEST_PAYMENT_PERMISSION', desc: '', hasParams: false, defaultData: null, responseSample: "{\"permissionCode\":\"...\",\"result\":\"...\",\"message\":\"...\"}" },
      { name: 'requestLoginPermission', event: 'REQUEST_LOGIN_PERMISSION', desc: '', hasParams: false, defaultData: null, responseSample: "{\"permissionCode\":\"...\",\"result\":\"...\",\"message\":\"...\"}" },
      { name: 'requestLocalAuthenticationPermission', event: 'REQUEST_LOCAL_AUTHENTICATION_PERMISSION', desc: 'Yêu cầu xác thực sinh trắc học (vân tay, Face ID).', hasParams: false, defaultData: null, responseSample: "{\"permissionCode\":\"...\",\"result\":\"...\",\"message\":\"...\"}" },
      { name: 'executeLocalAuthentication', event: 'EXECUTE_LOCAL_AUTHENTICATION', desc: 'Thực hiện xác thực sinh trắc học (vân tay, Face ID).', hasParams: true, defaultData: '{"data":{"authOptionsParam":{"sensitiveTransaction":true,"authClassification":["WEAK","STRONG","DEVICE"],"sticky":false,"isShowErrorDialog":true}}}', responseSample: "{\"result\":\"...\",\"description\":\"...\"}" }
    ] },
    { title: 'Device Check Permission', events: [
      { name: 'checkCameraPermission', event: 'CHECK_CAMERA_PERMISSION', desc: 'Kiểm tra quyền camera', hasParams: false, defaultData: null, responseSample: "{\"permissionCode\":\"...\",\"result\":\"...\",\"message\":\"...\"}" },
      { name: 'checkLocationPermission', event: 'CHECK_LOCATION_PERMISSION', desc: 'Kiểm tra quyền vị trí', hasParams: false, defaultData: null, responseSample: "{\"permissionCode\":\"...\",\"result\":\"...\",\"message\":\"...\"}" },
      { name: 'checkPhotosPermission', event: 'CHECK_PHOTOS_PERMISSION', desc: 'Kiểm tra quyền truy cập ảnh', hasParams: false, defaultData: null, responseSample: "{\"permissionCode\":\"...\",\"result\":\"...\",\"message\":\"...\"}" },
      { name: 'checkVideosPermission', event: 'CHECK_VIDEOS_PERMISSION', desc: 'Kiểm tra quyền truy cập video', hasParams: false, defaultData: null, responseSample: "{\"permissionCode\":\"...\",\"result\":\"...\",\"message\":\"...\"}" },
      { name: 'checkAudioPermission', event: 'CHECK_AUDIO_PERMISSION', desc: 'Kiểm tra quyền truy cập file audio', hasParams: false, defaultData: null, responseSample: "{\"permissionCode\":\"...\",\"result\":\"...\",\"message\":\"...\"}" },
      { name: 'checkRecordAudioPermission', event: 'CHECK_RECORD_AUDIO_PERMISSION', desc: 'Kiểm tra quyền ghi âm trên thiết bị', hasParams: false, defaultData: null, responseSample: "{\"permissionCode\":\"...\",\"result\":\"...\",\"message\":\"...\"}" },
      { name: 'checkContactsPermission', event: 'CHECK_CONTACTS_PERMISSION', desc: 'Kiểm tra quyền truy cập danh bạ', hasParams: false, defaultData: null, responseSample: "{\"permissionCode\":\"...\",\"result\":\"...\",\"message\":\"...\"}" },
      { name: 'checkDocumentPermission', event: 'CHECK_DOCUMENT_PERMISSION', desc: 'Kiểm tra quyền truy cập file tài liệu', hasParams: false, defaultData: null, responseSample: "{\"permissionCode\":\"...\",\"result\":\"...\",\"message\":\"...\"}" },
      { name: 'checkPaymentPermission', event: 'CHECK_PAYMENT_PERMISSION', desc: '', hasParams: false, defaultData: null, responseSample: "{\"permissionCode\":\"...\",\"result\":\"...\",\"message\":\"...\"}" },
      { name: 'checkLoginPermission', event: 'CHECK_LOGIN_PERMISSION', desc: '', hasParams: false, defaultData: null, responseSample: "{\"permissionCode\":\"...\",\"result\":\"...\",\"message\":\"...\"}" },
      { name: 'checkLocalAuthenticationPermission', event: 'CHECK_LOCAL_AUTHENTICATION_PERMISSION', desc: 'kiểm tra quyền xác thực sinh trắc học (vân tay, Face ID).', hasParams: false, defaultData: null, responseSample: "{\"permissionCode\":\"...\",\"result\":\"...\",\"message\":\"...\"}" }
    ] },
    { title: 'Storage', events: [
      { name: 'saveStringValue', event: 'SAVE_STRING_VALUE', desc: 'Lưu giá trị kiểu string.', hasParams: true, defaultData: '{"data":{"key":"user_preference","value":"dark_mode"}}', responseSample: null },
      { name: 'saveBooleanValue', event: 'SAVE_BOOLEAN_VALUE', desc: 'Lưu giá trị kiểu boolean.', hasParams: true, defaultData: '{"data":{"key":"notifications_enabled","value":true}}', responseSample: null },
      { name: 'saveIntegerValue', event: 'SAVE_INTEGER_VALUE', desc: 'Lưu giá trị kiểu int.', hasParams: true, defaultData: '{"data":{"key":"login_count","value":5}}', responseSample: null },
      { name: 'saveLongValue', event: 'SAVE_LONG_VALUE', desc: 'Lưu giá trị kiểu long.', hasParams: true, defaultData: '{"data":{"key":"last_sync_timestamp","value":1234567890}}', responseSample: null },
      { name: 'saveFloatValue', event: 'SAVE_FLOAT_VALUE', desc: 'Lưu giá trị kiểu float.', hasParams: true, defaultData: '{"data":{"key":"rating","value":4.5}}', responseSample: null },
      { name: 'getStringValue', event: 'GET_STRING_VALUE', desc: 'Lấy giá trị kiểu string.', hasParams: true, defaultData: '{"data":{"key":"user_preference","defaultValue":"light_mode"}}', responseSample: "{\"value\":\"...\"}" },
      { name: 'getBooleanValue', event: 'GET_BOOLEAN_VALUE', desc: 'Lấy giá trị kiểu boolean.', hasParams: true, defaultData: '{"data":{"key":"notifications_enabled","defaultValue":false}}', responseSample: "{\"value\":true}" },
      { name: 'getIntegerValue', event: 'GET_INTEGER_VALUE', desc: 'Lấy giá trị kiểu int.', hasParams: true, defaultData: '{"data":{"key":"...","defaultValue":0}}', responseSample: "{\"value\":0}" },
      { name: 'getLongValue', event: 'GET_LONG_VALUE', desc: 'Lấy giá trị kiểu long.', hasParams: true, defaultData: '{"data":{"key":"...","defaultValue":0}}', responseSample: "{\"value\":0}" },
      { name: 'getFloatValue', event: 'GET_FLOAT_VALUE', desc: 'Lấy giá trị kiểu float.', hasParams: true, defaultData: '{"data":{"key":"...","defaultValue":"..."}}', responseSample: "{\"value\":\"...\"}" },
      { name: 'clearStorage', event: 'CLEAR_STORAGE', desc: 'Lấy giá trị kiểu float.', hasParams: false, defaultData: null, responseSample: null }
    ] },
    { title: 'UI', events: [
      { name: 'updateMiniAppTheme', event: 'UPDATE_MINI_APP_THEME', desc: 'Update mini app theme', hasParams: true, defaultData: '{"data":{"headerColor":"#FFFFFF","headerTitle":"Mini App","textColor":"#EE0033","leftButton":"back","actionButtonThemeType":"light","hideAndroidBottomNavigationBar":false,"hideIOSSafeAreaBottom":false,"toolbarMode":"normal"}}', responseSample: null },
      { name: 'setScreenBrightness', event: 'SET_SCREEN_BRIGHTNESS', desc: 'Đặt độ sáng màn hình (screen-scoped) cho màn hình mini-app đang hiển thị. Tự khôi phục khi rời màn/nền.', hasParams: true, defaultData: '{"data":{"value":0.8}}', responseSample: "{\"data\":{\"success\":true}}" },
      { name: 'restoreScreenBrightness', event: 'RESTORE_SCREEN_BRIGHTNESS', desc: 'Khôi phục độ sáng về giá trị đã lưu gần nhất theo session mini-app.', hasParams: true, defaultData: '{"data":{}}', responseSample: "{\"data\":{\"success\":true}}" }
    ] }
  ];

  private logFor(name: string, msg: string, data?: any): void {
    const entry = data ? `${msg}: ${JSON.stringify(data, null, 2)}` : msg;
    if (!this.eventLogs[name]) this.eventLogs[name] = [];
    this.eventLogs[name] = [`[${new Date().toLocaleTimeString()}] ${entry}`, ...this.eventLogs[name]];
  }

  async runEvent(evt: EventInfo): Promise<void> {
    const fn = this.fns[evt.name];
    if (!fn) return;
    try {
      this.logFor(evt.name, `> ${evt.name}...`);
      // Promise.resolve boc lai vi ham MOT CHIEU tra ve void: entry khong khai
      // response trong hop dong thi khong co gi de doi, va goi thang .then tren
      // mot gia tri undefined la TypeError lam ca trang demo dung lai.
      const res = await Promise.resolve(fn() as any);
      this.logFor(evt.name, res === undefined ? `OK ${evt.name} — MOT CHIEU, khong co tra loi` : `OK ${evt.name}`, res);
    } catch (err) {
      this.logFor(evt.name, `ERR ${evt.name}`, err);
    }
  }

  private lsKey(name: string): string { return `webview_sdk_input_${name}`; }

  fillInput(evt: EventInfo): void {
    const saved = localStorage.getItem(this.lsKey(evt.name));
    if (saved) { try { this.inputs[evt.name] = JSON.stringify(JSON.parse(saved), null, 2); } catch { this.inputs[evt.name] = saved; } }
    else if (evt.defaultData) { this.inputs[evt.name] = JSON.stringify(JSON.parse(evt.defaultData), null, 2); }
  }

  saveInput(evt: EventInfo): void {
    const v = (this.inputs[evt.name] || '').trim();
    if (v) localStorage.setItem(this.lsKey(evt.name), v);
  }

  deleteInput(evt: EventInfo): void {
    localStorage.removeItem(this.lsKey(evt.name));
  }

  clearLog(name: string): void {
    this.eventLogs[name] = [];
  }

  showPopup(evt: EventInfo): void {
    this.popup = this.popup?.name === evt.name ? null : evt;
    this.rawText = null;
  }

  showInvoke(): void {
    this.showPopup({ name: 'invoke', event: 'INVOKE', desc: '', hasParams: true, defaultData: null, responseSample: null });
  }

  private payloadFor(evt: EventInfo): any {
    const typed = this.getInputFor_(evt.name);
    if (typed) return typed;
    if (evt.defaultData) { try { return JSON.parse(evt.defaultData); } catch { /* input hong thi coi nhu rong */ } }
    return {};
  }

  toggleRaw(evt: EventInfo): void {
    this.rawText = this.rawText ? null : buildRawSnippet(evt.event, this.payloadFor(evt), evt.responseSample);
  }

  copyRaw(): void {
    copyText(this.rawText || '');
  }
}
